/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StagesRouteImport } from './routes/stages'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as PersonalFilesRouteImport } from './routes/personal-files'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ContractorsRouteImport } from './routes/contractors'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as BoqwizardRouteImport } from './routes/boqwizard'
import { Route as BoqRouteImport } from './routes/boq'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinCodeRouteImport } from './routes/join.$code'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesRoute = StagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalFilesRoute = PersonalFilesRouteImport.update({
  id: '/personal-files',
  path: '/personal-files',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsRoute = ContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const BoqwizardRoute = BoqwizardRouteImport.update({
  id: '/boqwizard',
  path: '/boqwizard',
  getParentRoute: () => rootRouteImport,
} as any)
const BoqRoute = BoqRouteImport.update({
  id: '/boq',
  path: '/boq',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/boq': typeof BoqRoute
  '/boqwizard': typeof BoqwizardRoute
  '/budget': typeof BudgetRoute
  '/checklists': typeof ChecklistsRoute
  '/contractors': typeof ContractorsRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/personal-files': typeof PersonalFilesRoute
  '/photos': typeof PhotosRoute
  '/projects': typeof ProjectsRoute
  '/quotes': typeof QuotesRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/stages': typeof StagesRoute
  '/team': typeof TeamRoute
  '/timeline': typeof TimelineRoute
  '/join/$code': typeof JoinCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/boq': typeof BoqRoute
  '/boqwizard': typeof BoqwizardRoute
  '/budget': typeof BudgetRoute
  '/checklists': typeof ChecklistsRoute
  '/contractors': typeof ContractorsRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/personal-files': typeof PersonalFilesRoute
  '/photos': typeof PhotosRoute
  '/projects': typeof ProjectsRoute
  '/quotes': typeof QuotesRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/stages': typeof StagesRoute
  '/team': typeof TeamRoute
  '/timeline': typeof TimelineRoute
  '/join/$code': typeof JoinCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/boq': typeof BoqRoute
  '/boqwizard': typeof BoqwizardRoute
  '/budget': typeof BudgetRoute
  '/checklists': typeof ChecklistsRoute
  '/contractors': typeof ContractorsRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/personal-files': typeof PersonalFilesRoute
  '/photos': typeof PhotosRoute
  '/projects': typeof ProjectsRoute
  '/quotes': typeof QuotesRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/stages': typeof StagesRoute
  '/team': typeof TeamRoute
  '/timeline': typeof TimelineRoute
  '/join/$code': typeof JoinCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/boq'
    | '/boqwizard'
    | '/budget'
    | '/checklists'
    | '/contractors'
    | '/landing'
    | '/login'
    | '/notes'
    | '/personal-files'
    | '/photos'
    | '/projects'
    | '/quotes'
    | '/register'
    | '/setup'
    | '/stages'
    | '/team'
    | '/timeline'
    | '/join/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/boq'
    | '/boqwizard'
    | '/budget'
    | '/checklists'
    | '/contractors'
    | '/landing'
    | '/login'
    | '/notes'
    | '/personal-files'
    | '/photos'
    | '/projects'
    | '/quotes'
    | '/register'
    | '/setup'
    | '/stages'
    | '/team'
    | '/timeline'
    | '/join/$code'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/boq'
    | '/boqwizard'
    | '/budget'
    | '/checklists'
    | '/contractors'
    | '/landing'
    | '/login'
    | '/notes'
    | '/personal-files'
    | '/photos'
    | '/projects'
    | '/quotes'
    | '/register'
    | '/setup'
    | '/stages'
    | '/team'
    | '/timeline'
    | '/join/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BoqRoute: typeof BoqRoute
  BoqwizardRoute: typeof BoqwizardRoute
  BudgetRoute: typeof BudgetRoute
  ChecklistsRoute: typeof ChecklistsRoute
  ContractorsRoute: typeof ContractorsRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  PersonalFilesRoute: typeof PersonalFilesRoute
  PhotosRoute: typeof PhotosRoute
  ProjectsRoute: typeof ProjectsRoute
  QuotesRoute: typeof QuotesRoute
  RegisterRoute: typeof RegisterRoute
  SetupRoute: typeof SetupRoute
  StagesRoute: typeof StagesRoute
  TeamRoute: typeof TeamRoute
  TimelineRoute: typeof TimelineRoute
  JoinCodeRoute: typeof JoinCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages': {
      id: '/stages'
      path: '/stages'
      fullPath: '/stages'
      preLoaderRoute: typeof StagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-files': {
      id: '/personal-files'
      path: '/personal-files'
      fullPath: '/personal-files'
      preLoaderRoute: typeof PersonalFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors': {
      id: '/contractors'
      path: '/contractors'
      fullPath: '/contractors'
      preLoaderRoute: typeof ContractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boqwizard': {
      id: '/boqwizard'
      path: '/boqwizard'
      fullPath: '/boqwizard'
      preLoaderRoute: typeof BoqwizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boq': {
      id: '/boq'
      path: '/boq'
      fullPath: '/boq'
      preLoaderRoute: typeof BoqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BoqRoute: BoqRoute,
  BoqwizardRoute: BoqwizardRoute,
  BudgetRoute: BudgetRoute,
  ChecklistsRoute: ChecklistsRoute,
  ContractorsRoute: ContractorsRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  PersonalFilesRoute: PersonalFilesRoute,
  PhotosRoute: PhotosRoute,
  ProjectsRoute: ProjectsRoute,
  QuotesRoute: QuotesRoute,
  RegisterRoute: RegisterRoute,
  SetupRoute: SetupRoute,
  StagesRoute: StagesRoute,
  TeamRoute: TeamRoute,
  TimelineRoute: TimelineRoute,
  JoinCodeRoute: JoinCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
