/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingNewProjectRouteImport } from './routes/onboarding.new-project'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppStagesRouteImport } from './routes/app.stages'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppFilesRouteImport } from './routes/app.files'
import { Route as AppBudgetRouteImport } from './routes/app.budget'
import { Route as AppSuppliersSupplierIdRouteImport } from './routes/app.suppliers.$supplierId'
import { Route as AppStagesStageIdRouteImport } from './routes/app.stages.$stageId'
import { Route as AppBudgetCategoryIdRouteImport } from './routes/app.budget.$categoryId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingNewProjectRoute = OnboardingNewProjectRouteImport.update({
  id: '/onboarding/new-project',
  path: '/onboarding/new-project',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppStagesRoute = AppStagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersSupplierIdRoute = AppSuppliersSupplierIdRouteImport.update({
  id: '/$supplierId',
  path: '/$supplierId',
  getParentRoute: () => AppSuppliersRoute,
} as any)
const AppStagesStageIdRoute = AppStagesStageIdRouteImport.update({
  id: '/$stageId',
  path: '/$stageId',
  getParentRoute: () => AppStagesRoute,
} as any)
const AppBudgetCategoryIdRoute = AppBudgetCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => AppBudgetRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/budget': typeof AppBudgetRouteWithChildren
  '/app/files': typeof AppFilesRoute
  '/app/home': typeof AppHomeRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/stages': typeof AppStagesRouteWithChildren
  '/app/suppliers': typeof AppSuppliersRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/onboarding/new-project': typeof OnboardingNewProjectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/budget/$categoryId': typeof AppBudgetCategoryIdRoute
  '/app/stages/$stageId': typeof AppStagesStageIdRoute
  '/app/suppliers/$supplierId': typeof AppSuppliersSupplierIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/budget': typeof AppBudgetRouteWithChildren
  '/app/files': typeof AppFilesRoute
  '/app/home': typeof AppHomeRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/stages': typeof AppStagesRouteWithChildren
  '/app/suppliers': typeof AppSuppliersRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/onboarding/new-project': typeof OnboardingNewProjectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/budget/$categoryId': typeof AppBudgetCategoryIdRoute
  '/app/stages/$stageId': typeof AppStagesStageIdRoute
  '/app/suppliers/$supplierId': typeof AppSuppliersSupplierIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/budget': typeof AppBudgetRouteWithChildren
  '/app/files': typeof AppFilesRoute
  '/app/home': typeof AppHomeRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/stages': typeof AppStagesRouteWithChildren
  '/app/suppliers': typeof AppSuppliersRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/onboarding/new-project': typeof OnboardingNewProjectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/budget/$categoryId': typeof AppBudgetCategoryIdRoute
  '/app/stages/$stageId': typeof AppStagesStageIdRoute
  '/app/suppliers/$supplierId': typeof AppSuppliersSupplierIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/budget'
    | '/app/files'
    | '/app/home'
    | '/app/payments'
    | '/app/projects'
    | '/app/stages'
    | '/app/suppliers'
    | '/auth/login'
    | '/onboarding/new-project'
    | '/api/auth/$'
    | '/app/budget/$categoryId'
    | '/app/stages/$stageId'
    | '/app/suppliers/$supplierId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/budget'
    | '/app/files'
    | '/app/home'
    | '/app/payments'
    | '/app/projects'
    | '/app/stages'
    | '/app/suppliers'
    | '/auth/login'
    | '/onboarding/new-project'
    | '/api/auth/$'
    | '/app/budget/$categoryId'
    | '/app/stages/$stageId'
    | '/app/suppliers/$supplierId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/budget'
    | '/app/files'
    | '/app/home'
    | '/app/payments'
    | '/app/projects'
    | '/app/stages'
    | '/app/suppliers'
    | '/auth/login'
    | '/onboarding/new-project'
    | '/api/auth/$'
    | '/app/budget/$categoryId'
    | '/app/stages/$stageId'
    | '/app/suppliers/$supplierId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  OnboardingNewProjectRoute: typeof OnboardingNewProjectRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/new-project': {
      id: '/onboarding/new-project'
      path: '/onboarding/new-project'
      fullPath: '/onboarding/new-project'
      preLoaderRoute: typeof OnboardingNewProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stages': {
      id: '/app/stages'
      path: '/stages'
      fullPath: '/app/stages'
      preLoaderRoute: typeof AppStagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/files': {
      id: '/app/files'
      path: '/files'
      fullPath: '/app/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/budget': {
      id: '/app/budget'
      path: '/budget'
      fullPath: '/app/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers/$supplierId': {
      id: '/app/suppliers/$supplierId'
      path: '/$supplierId'
      fullPath: '/app/suppliers/$supplierId'
      preLoaderRoute: typeof AppSuppliersSupplierIdRouteImport
      parentRoute: typeof AppSuppliersRoute
    }
    '/app/stages/$stageId': {
      id: '/app/stages/$stageId'
      path: '/$stageId'
      fullPath: '/app/stages/$stageId'
      preLoaderRoute: typeof AppStagesStageIdRouteImport
      parentRoute: typeof AppStagesRoute
    }
    '/app/budget/$categoryId': {
      id: '/app/budget/$categoryId'
      path: '/$categoryId'
      fullPath: '/app/budget/$categoryId'
      preLoaderRoute: typeof AppBudgetCategoryIdRouteImport
      parentRoute: typeof AppBudgetRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppBudgetRouteChildren {
  AppBudgetCategoryIdRoute: typeof AppBudgetCategoryIdRoute
}

const AppBudgetRouteChildren: AppBudgetRouteChildren = {
  AppBudgetCategoryIdRoute: AppBudgetCategoryIdRoute,
}

const AppBudgetRouteWithChildren = AppBudgetRoute._addFileChildren(
  AppBudgetRouteChildren,
)

interface AppStagesRouteChildren {
  AppStagesStageIdRoute: typeof AppStagesStageIdRoute
}

const AppStagesRouteChildren: AppStagesRouteChildren = {
  AppStagesStageIdRoute: AppStagesStageIdRoute,
}

const AppStagesRouteWithChildren = AppStagesRoute._addFileChildren(
  AppStagesRouteChildren,
)

interface AppSuppliersRouteChildren {
  AppSuppliersSupplierIdRoute: typeof AppSuppliersSupplierIdRoute
}

const AppSuppliersRouteChildren: AppSuppliersRouteChildren = {
  AppSuppliersSupplierIdRoute: AppSuppliersSupplierIdRoute,
}

const AppSuppliersRouteWithChildren = AppSuppliersRoute._addFileChildren(
  AppSuppliersRouteChildren,
)

interface AppRouteChildren {
  AppBudgetRoute: typeof AppBudgetRouteWithChildren
  AppFilesRoute: typeof AppFilesRoute
  AppHomeRoute: typeof AppHomeRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppStagesRoute: typeof AppStagesRouteWithChildren
  AppSuppliersRoute: typeof AppSuppliersRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetRoute: AppBudgetRouteWithChildren,
  AppFilesRoute: AppFilesRoute,
  AppHomeRoute: AppHomeRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppStagesRoute: AppStagesRouteWithChildren,
  AppSuppliersRoute: AppSuppliersRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  OnboardingNewProjectRoute: OnboardingNewProjectRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
